name: Teste GitHub Actions

on:
    push:
    schedule:
        - cron: 0 * * * *

jobs:
    job1:
        name: build and test code
        runs-on: ubuntu-latest  
        steps:
            - uses: actions/checkout@v4
            - name: Setup-dotnet
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '6.0.x'
            - name: Install dependencies
              run: dotnet restore myprojectexample.csproj
            
    job2:
        name: chatgpt-check-code
        runs-on: ubuntu-latest
        steps:
            - uses: anc95/ChatGPT-CodeReview@main
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    job3:
        name: checks-status
        needs: job2
        runs-on: ubuntu-latest
        steps:
            - run: echo 'Status ${{ job.status }}'
        