name: Teste GitHub Actions

on:
    push:
    schedule:
        - cron: 0 * * * *

jobs:
    job1:
        name: checks-commits
        runs-on: ubuntu-latest  
        steps:
            - uses: actions/checkout@v4
            - uses: commit-check/commit-check-action@v1
              with:
                message: true
                branch: true
                author-name: true
                author-email: true
                commit-signoff: true
                job-summary: true
    job2:
        runs-on: ubuntu-latest
        name: create-pull-request
        uses: peter-evans/create-pull-request@v6
        with:
            commit-message: 'chore: update used-by badge by github-actions[bot]'
            base: main

    job3:
        name: checks-status
        needs: job2
        runs-on: ubuntu-latest
        steps:
            - run: echo 'Status ${{ job.status }}'
        